- name: Enable stonith
  command: pcs property set stonith-enabled=true
  register: stonith
  changed_when: "'error' not in stonith.stdout"
  run_once: true

- name: Create stonith device for host1
  command: >
    pcs stonith create {{ sap_hana_ha_pacemaker_node1_fencing_device.name }} {{ sap_hana_ha_pacemaker_node1_fencing_device.type }}
    ipaddr={{ sap_hana_ha_pacemaker_node1_fencing_device.ip }} login={{ sap_hana_ha_pacemaker_node1_fencing_device.user }}
    passwd={{ sap_hana_ha_pacemaker_node1_fencing_device.pwd }} port=={{ sap_hana_ha_pacemaker_node1_fencing_device.port }}   
    pcmk_host_list={{ sap_hana_ha_pacemaker_node1_fencing_device.pcmk_host_list }} op monitor interval=30
  register: stonith1_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true

- name: Create stonith device for host2
  command: >
    pcs stonith create {{ sap_hana_ha_pacemaker_node2_fencing_device.name }} {{ sap_hana_ha_pacemaker_node2_fencing_device.type }}
    ipaddr={{ sap_hana_ha_pacemaker_node2_fencing_device.ip }} login={{ sap_hana_ha_pacemaker_node2_fencing_device.user }}
    passwd={{ sap_hana_ha_pacemaker_node2_fencing_device.pwd }} port=={{ sap_hana_ha_pacemaker_node2_fencing_device.port }}   
    pcmk_host_list={{ sap_hana_ha_pacemaker_node2_fencing_device.pcmk_host_list }} op monitor interval=30
  register: stonith2_device
  changed_when: "'error' not in stonith_device.stdout"
  run_once: true
